All three cases passed
goharsimonyann/aobyte-internship-gohar-simonyan pull request #3
Opened 2023-07-04 06:45 UTC by goharsimonyann

2023-07-05 13:21 UTC, aokareng requested changes
Good Job Gohar jan! 
There are some things You could write better, but anyway, The main logic and class implementations are good.

2023-07-05 13:21 UTC, aokareng commented on N2/js/DomElement.js
> +const tagnames = {
The same thing about to the naming convention for variable names

2023-07-05 13:21 UTC, aokareng commented on N2/js/DomElement.js
> +function el(tagname, options, children) {
Gohar the function would be much simple if you write just multiple IF statements, ELSE IF is redundant, because You are using the RETURN keyword, and it ends JavaScript code execution (You can use this advice for the future too).

Eg. if (tagnames[tagname]) {
    return new tagnames[tagname](options, children);
  }
  
  if(Object.values(tagnames).includes(tagname)) {
  return ....
  }
  
  return ...

2023-07-05 13:21 UTC, aokareng commented on N2/js/DomElement.js
> +  } else if (Object.values(tagnames).includes(tagname)) {
Also, You can assign Object.values(tagnames) to a variable and then use it multiple times as I said above.
Eg.
let tagNameValues = Object.values(tagnames);
if(tagNameValues.includes(tagname)) {
    const index = tagNameValues.indexOf(tagname);
    ...
}

2023-07-06 10:28 UTC, goharsimonyann commented
Thank you for your valuable feedback and suggestions. I made the necessary changes in this pull request. 
The changes are now ready for your review. 

Thank you once again!

2023-07-06 10:34 UTC, aokareng commented
> Thank you for your valuable feedback and suggestions. I made the necessary changes in this pull request. The changes are now ready for your review.
> 
> Thank you once again!

Gohar jan, mark as 'Resolved' the comment(s) when you are fixing it.

2023-07-06 19:29 UTC, merged